---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dynamic-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.33.10-192.168.33.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.30.10-192.168.30.250
  autoAssign: false
