services:
  lancache:
    container_name: steamcache
    image: "lancachenet/monolithic:latest"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/data/steam/cache:/data/cache",
      - "/var/log/lancache:/data/logs"
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"