server:

   local-zone: "gssn.xyz" static

   #storage
   local-data: "marvin.gssn.xyz IN A 192.168.99.99"
   local-data: "zaphod.gssn.xyz IN A 192.168.99.100"

   #network
   local-data: "mt1.gssn.xyz IN A 192.168.88.1"
   local-data: "zx1.gssn.xyz IN A 192.168.88.2"

   #infra
   local-data: "xo.gssn.xyz IN A 192.168.0.130"
   local-data: "minix.gssn.xyz IN A 192.168.80.6"

   #applications
   local-data: "homeassistant.gssn.xyz IN A 192.168.5.6"
   local-data: "media.gssn.xyz IN A 192.168.80.85"
   local-data: "jellyfin.gssn.xyz IN A 192.168.80.85"
   local-data: "smt.gssn.xyz IN A 192.168.80.85"
   local-data: "git.gssn.xyz IN A 192.168.100.1"