apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: root@gssn.xyz
    privateKeySecretRef:
      name: le-prod-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector: {}
        dns01:
          webhook:
            groupName: acme.infomaniak.com
            solverName: infomaniak
            config:
              apiTokenSecretRef:
                name: infomaniak-api-credentials
                key: api-token