services:
  jellyfin:
    container_name: jellyfin
    image: "jellyfin/jellyfin"
    user: 1000:1000
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /data/Videos
        target: /media
        read_only: true
    restart: unless-stopped
    privileged: true
    network_mode: host
