infra:
  hosts:
    dns:
      ansible_host: dns.gssn.net
    vpn:
      ansible_host: vpn.gssn.net
    xo:
      ansible_host: xo.gssn.net
    bastion:
      ansible_host: bastion.gssn.net
    ansible:
      ansible_host: ansible.gssn.net
    mini-xcp:
      ansible_host: mini-xcp.gssn.net
    lab-xcp:
      ansible_host: lab-xcp.gssn.net
    borg1:
      ansible_host: borg1.gssn.net
    borg2:
      ansible_host: borg2.gssn.net
    borg3:
      ansible_host: borg3.gssn.net
    id:
      ansible_host: id.gssn.net
storage:
  hosts:
    vulcanDb:
      ansible_host: vulcandb.gssn.net
automation:
  hosts:
    homeAssistant:
      ansible_host: homeassistant.gssn.net