[storage]
vulcandb.local

[infra]
dns.gssn.net
vpn.gssn.net

[xcp]
eenie-xcp.gssn.net
mini-xcp.gssn.net
moo-xcp.gssn.net
lab-xcp.gssn.net
ryzen-xcp.gssn.net

[xenvm]
xo.gssn.net
bastion.gssn.net
ansible.gssn.net
ipa.gssn.net
cargo.gssn.net

[k8s]
borg[01:04].gssn.net

[automation]
homeassistant.gssn.net

[observability]
prometheus.gssn.net
grafana.gssn.net
obs.gssn.net

[debian]
vulcandb.local
dns.gssn.net
vpn.gssn.net
borg[01:04].gssn.net
xo.gssn.net
bastion.gssn.net
ansible.gssn.net
cargo.gssn.net
obs.gssn.net

[fedora]
ipa.gssn.net

[docker]
grafana.gssn.net

[down]
borg01.gssn.net
borg02.gssn.net
borg04.gssn.net
ansible.gssn.net
